use crate::boards;
use std::fs;

const MAIN_ZIG: &str = r#"pub fn main() void {
    // Your bare metal code here
}
"#;

const START_ZIG: &str = r#"//! Startup code generated by rvkit — do not edit.
//! Sets up the stack pointer, copies .data from flash to RAM, zeroes .bss,
//! then calls main(). The symbols come from the linker script.

const main_entry = @import("main.zig").main;

extern var _sdata: u8;
extern var _edata: u8;
extern var _sbss: u8;
extern var _ebss: u8;
extern const _etext: u8;

export fn _start() linksection(".init") callconv(.naked) noreturn {
    asm volatile (
        \\la sp, _stack_top
        \\j _start_zig
    );
}

export fn _start_zig() callconv(.c) noreturn {
    const data_len = @intFromPtr(&_edata) - @intFromPtr(&_sdata);
    const data_src: [*]const u8 = @ptrCast(&_etext);
    const data_dst: [*]u8 = @ptrCast(&_sdata);
    for (0..data_len) |i| data_dst[i] = data_src[i];

    const bss_len = @intFromPtr(&_ebss) - @intFromPtr(&_sbss);
    const bss: [*]u8 = @ptrCast(&_sbss);
    for (0..bss_len) |i| bss[i] = 0;

    main_entry();
    while (true) {}
}
"#;

const BUILD_ZIG: &str = r#"const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.resolveTargetQuery(.{
@TARGET_QUERY@
    });

    const exe = b.addExecutable(.{
        .name = "@NAME@",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/start.zig"),
            .target = target,
            .optimize = .ReleaseSmall,
        }),
    });

    exe.setLinkerScript(b.path("linker/@BOARD@.ld"));

    b.installArtifact(exe);
}
"#;

const RVKIT_TOML: &str = r#"[project]
name = "@NAME@"
board = "@BOARD@"

# Optional serial port settings used by `rvkit monitor`
# [flash]
# port = "/dev/ttyUSB0"   # COM3 on Windows
# baud_rate = 115200
"#;

fn validate_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("project name cannot be empty".to_string());
    }
    if let Some(c) = name
        .chars()
        .find(|c| !c.is_ascii_alphanumeric() && *c != '_' && *c != '-')
    {
        return Err(format!(
            "project name contains invalid character '{}' (allowed: letters, digits, '_', '-')",
            c
        ));
    }
    Ok(())
}

pub fn run(board_name: &str, name: &str) {
    let board = boards::get(board_name).unwrap_or_else(|| {
        eprintln!(
            "Board '{}' is not supported. Run 'rvkit boards' to see available boards.",
            board_name
        );
        std::process::exit(1);
    });

    if let Err(e) = validate_name(name) {
        eprintln!("Error: {}.", e);
        std::process::exit(1);
    }

    if board.experimental {
        println!(
            "warning: '{}' support is experimental — the project scaffolds and builds, but 'rvkit flash' is not implemented for it yet.",
            board.name
        );
    }

    println!("Creating project '{}' for board '{}'...", name, board.name);

    let cwd = std::env::current_dir().unwrap_or_else(|_| {
        eprintln!("Error: cannot determine current directory.");
        std::process::exit(1);
    });
    let root = cwd.join(name);
    if root.exists() {
        eprintln!("Error: directory '{}' already exists.", name);
        std::process::exit(1);
    }

    fs::create_dir_all(root.join("src")).expect("Failed to create src/");
    fs::create_dir_all(root.join("linker")).expect("Failed to create linker/");

    fs::write(
        root.join("linker").join(format!("{}.ld", board.name)),
        board.linker_script,
    )
    .expect("Failed to write linker script");

    let toml = RVKIT_TOML
        .replace("@NAME@", name)
        .replace("@BOARD@", board.name);
    fs::write(root.join("rvkit.toml"), toml).expect("Failed to write rvkit.toml");

    fs::write(root.join("src/main.zig"), MAIN_ZIG).expect("Failed to write main.zig");
    fs::write(root.join("src/start.zig"), START_ZIG).expect("Failed to write start.zig");

    let build_zig = BUILD_ZIG
        .replace("@TARGET_QUERY@", board.target_query)
        .replace("@NAME@", name)
        .replace("@BOARD@", board.name);
    fs::write(root.join("build.zig"), build_zig).expect("Failed to write build.zig");

    println!("✓ Project '{}' created for board '{}'", name, board.name);
    println!("  → cd {}", name);
    println!("  → rvkit build");
}
